package pl.jangrot.katas.berlinclock

import spock.lang.Specification

class OneFullMinuteLampsSpec extends Specification {
    def "The next OneMinuteHourLamp lights up every 1 hour"() {
        expect:
        new OneFullMinuteLamps(minutes).get() == result
        where:
        minutes || result
        0       || "OOOO"
        1       || "YOOO"
        2       || "YYOO"
        3       || "YYYO"
        4       || "YYYY"
        5       || "OOOO"
        6       || "YOOO"
        7       || "YYOO"
        8       || "YYYO"
        9       || "YYYY"
        10      || "OOOO"
        11      || "YOOO"
        12      || "YYOO"
        13      || "YYYO"
        14      || "YYYY"
        15      || "OOOO"
        16      || "YOOO"
        17      || "YYOO"
        18      || "YYYO"
        19      || "YYYY"
        20      || "OOOO"
        21      || "YOOO"
        22      || "YYOO"
        23      || "YYYO"
        24      || "YYYY"
        25      || "OOOO"
        26      || "YOOO"
        27      || "YYOO"
        28      || "YYYO"
        29      || "YYYY"
        30      || "OOOO"
        31      || "YOOO"
        32      || "YYOO"
        33      || "YYYO"
        34      || "YYYY"
        35      || "OOOO"
        36      || "YOOO"
        37      || "YYOO"
        38      || "YYYO"
        39      || "YYYY"
        40      || "OOOO"
        41      || "YOOO"
        42      || "YYOO"
        43      || "YYYO"
        44      || "YYYY"
        45      || "OOOO"
        46      || "YOOO"
        47      || "YYOO"
        48      || "YYYO"
        49      || "YYYY"
        50      || "OOOO"
        51      || "YOOO"
        52      || "YYOO"
        53      || "YYYO"
        54      || "YYYY"
        55      || "OOOO"
        56      || "YOOO"
        57      || "YYOO"
        58      || "YYYO"
        59      || "YYYY"
    }
}
